
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5


test:
  <<: *default
  database: test_postgresql

production:
  <<: *default
  database: production_postgresql


production:
  <<: *default
  database: portfolio_production
  username: portfolio
  password: <%= ENV['PORTFOLIO_DATABASE_PASSWORD'] %>

